src/Entity/Affectations.php
<?php

namespace App\Entity;

use App\Repository\AffectationsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AffectationsRepository::class)]
class Affectations
{
     /**
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z]+$/",
     *     message="Username should only contain letters"
     * )
     */
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"Date Début Invalide")]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"Date Fin Invalide")]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[Assert\NotBlank(message:"ID Technicien Invalide")]
    private ?Technicien $technicien = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[Assert\NotBlank(message:"ID Terrain Invalide")]
    private ?Terrain $terrain = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getTechnicien(): ?Technicien
    {
        return $this->technicien;
    }

    public function setTechnicien(?Technicien $technicien): self
    {
        $this->technicien = $technicien;

        return $this;
    }

    public function getTerrain(): ?Terrain
    {
        return $this->terrain;
    }

    public function setTerrain(?Terrain $terrain): self
    {
        $this->terrain = $terrain;

        return $this;
    }
}

src/Form/AffectationsType.php
<?php

namespace App\Form;

use App\Entity\Affectations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
class AffectationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('technicien')
        ->add('terrain')
        ->add('date_debut')
        ->add('date_fin')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Affectations::class,
        ]);
    }
}

src/Controller/AffectationsController.php
<?php

namespace App\Controller;

use App\Entity\Affectations;
use App\Form\AffectationsType;
use App\Repository\AffectationsRepository;
use App\Repository\TechnicienRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/affectations')]
class AffectationsController extends AbstractController
{
    #[Route('/', name: 'app_affectations_index', methods: ['GET'])]
    public function index(Request $request ,AffectationsRepository $affectationsRepository,TechnicienRepository $TechnicienRepository, PaginatorInterface $paginator): Response
    {   
        $techs=$TechnicienRepository->findAll();
        foreach($techs as $t)
        {
            $catnom [] =$t->getNom();
            $nbr [] = $affectationsRepository->countAffectationsForTechnicien($t->getId());
        }
        $affectations=$affectationsRepository->findAll();
        $affectations=$paginator->paginate(
            $affectations, /* query NOT result */
            $request->query->getInt('page', 1),
            5
        );
        return $this->render('affectations/index.html.twig', [
            'affectations' =>$affectations,
            'technom' => json_encode($catnom),
            'nbr' => json_encode($nbr)
        ]);
    }
    #[Route('/stat', name: 'app_affectations_stat', methods: ['GET'])]
    public function stat(AffectationsRepository $affectationsRepository,TechnicienRepository $TechnicienRepository): Response
    {   
        $techs=$TechnicienRepository->findAll();
        foreach($techs as $t)
        {
            $catnom [] =$t->getNom();
            $nbr [] = $affectationsRepository->countAffectationsForTechnicien($t->getId());
        }
        $affectations=$affectationsRepository->findAll();

        return $this->render('affectations/stat.html.twig', [
            'affectations' =>$affectations,
            'technom' => json_encode($catnom),
            'nbr' => json_encode($nbr)
        ]);
    }

    #[Route('/calendar', name: 'app_affectations_calendar', methods: ['GET'])]
    public function calendar(AffectationsRepository $affectationsRepository)
    {
        $events = $affectationsRepository->findAll();

        $rdvs = [];

        foreach($events as $event){
            $rdvs[] = [
                'id' => $event->getId(),
                'Technicien' => $event->getTechnicien(),
                'Terrain' => $event->getTerrain(),
            ];
        }

        $data = json_encode($rdvs);

        return $this->render('affectations/calendar.html.twig', compact('data'));
    }

    #[Route('/afficher', name: 'app_affectations_afficher', methods: ['GET'])]
    public function afficher(Request $request ,AffectationsRepository $affectationsRepository, PaginatorInterface $paginator): Response
    {    $session= $request->getSession();
         $membre=$session->get('user');
        $affectations=$affectationsRepository->findByMembre($membre->getId());
        $affectations=$paginator->paginate(
            $affectations, /* query NOT result */
            $request->query->getInt('page', 1),
            5
        );
        return $this->render('affectations/afficher.html.twig', [
            'affectations' => $affectations,
            'user' => $membre
        ]);
    }
    
    #[Route('/new', name: 'app_affectations_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AffectationsRepository $affectationsRepository): Response
    {
        $affectation = new Affectations();
        $form = $this->createForm(AffectationsType::class, $affectation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $affectationsRepository->save($affectation, true);

            return $this->redirectToRoute('app_affectations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('affectations/new.html.twig', [
            'affectation' => $affectation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_affectations_show', methods: ['GET'])]
    public function show(Request $request,Affectations $affectation): Response
    {   $session= $request->getSession();
        $membre=$session->get('user');
        return $this->render('affectations/show.html.twig', [
            'affectation' => $affectation,
            'user' => $membre
        ]);
    }

    #[Route('/{id}/edit', name: 'app_affectations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Affectations $affectation, AffectationsRepository $affectationsRepository): Response
    {
        $form = $this->createForm(AffectationsType::class, $affectation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $affectationsRepository->save($affectation, true);

            return $this->redirectToRoute('app_affectations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('affectations/edit.html.twig', [
            'affectation' => $affectation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_affectations_delete', methods: ['POST'])]
    public function delete(Request $request, Affectations $affectation, AffectationsRepository $affectationsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$affectation->getId(), $request->request->get('_token'))) {
            $affectationsRepository->remove($affectation, true);
        }

        return $this->redirectToRoute('app_affectations_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/affectations/_delete_form.html.twig
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
<form method="post" action="{{ path('app_affectations_delete', {'id': affectation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ affectation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/affectations/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form, {'attr': {'class': 'form-control'}}) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/affectations/afficher.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
<div class="container">

<h1>Affectation</h1>
<br>
<table class="table" border="5" style="background-color: rgb(29,118,157,0.6)">
        <thead>
            <tr>
                <th>Nom Technicien</th>
                <th>ID Terrain</th>
                <th>Date Debut</th>
                <th>Date Fin</th>
            </tr>
        </thead>
        <tbody>

        {% for affectation in affectations %}
            <tr>
                <td>{{ affectation.technicien }}</td>
                <td>{{ affectation.terrain }}</td>
                <td>{{ affectation.dateDebut ? affectation.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ affectation.dateFin ? affectation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="affectationspagination">
        {{ knp_pagination_render(affectations) }}
    </div>
    </div>
{% endblock %}

templates/affectations/calendar.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Calendrier</h1>
    
    <table class="table">
        <a href="{{ path('app_affectations_index') }}"class="editlink">Back</a>
            <div id="calendrier"></div>


    </table>

{% block javascripts %}
<script>
    window.onload = () => {
        let calendarElt = document.querySelector("#calendrier")

        let calendar = new FullCalendar.Calendar(calendarElt, {
            initialView: 'dayGridMonth',
            locale: 'fr',
            timeZone: 'Europe/Paris',
            headerToolbar: {
                start: 'prev,next today',
                center: 'title',
                end: 'dayGridMonth,timeGridWeek'
            },
            {#events: {{ data|raw }}#}
            editable: true,
            eventResizableFromStart: true
        })

        calendar.on('eventChange', (e) => {
            let url = `/api/${e.event.id}/edit`
            let donnees = {
                "title": e.event.title,
                "description": e.event.extendedProps.description,
                "start": e.event.start,
                "end": e.event.end,
                "backgroundColor": e.event.backgroundColor,
                "borderColor": e.event.borderColor,
                "textColor": e.event.textColor,
                "allDay": e.event.allDay
            }
            
            let xhr = new XMLHttpRequest

            xhr.open("PUT", url)
            xhr.send(JSON.stringify(donnees))
        })

        calendar.render()
    }
</script>
{% endblock %}
{% endblock %}

templates/affectations/edit.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Affectations Edit{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Affectations Edit</h1>

    {{ include('affectations/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('app_affectations_index') }}" class="editlink">Back</a>
    {{ include('affectations/_delete_form.html.twig') }}
{% endblock %}

templates/affectations/index.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Affectations Listes{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Affectations Listes</h1>
 
    <table class="table">
        <thead>
            <tr>
                <th>ID Terrain</th>
                <th>Nom Technicien</th>
                <th>Date Debut</th>
                <th>Date Fin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <a href="{{ path('app_affectations_new') }}"class="editlink">Create</a>
            <a href="{{ path('app_affectations_calendar') }}"class="editlink">Calendrier</a>
            <a href="{{ path('app_affectations_stat') }}"class="editlink">Statistique</a>
        {% for affectation in affectations %}
            <tr>
                <td>{{ affectation.id }}</td>
                <td>{{ affectation.technicien }}</td>
                <td>{{ affectation.dateDebut ? affectation.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ affectation.dateFin ? affectation.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_affectations_show', {'id': affectation.id}) }}"class="editlink">Show</a>
                    <a href="{{ path('app_affectations_edit', {'id': affectation.id}) }}"class="editlink">Edit</a>
                    {{ include('affectations/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        

        </tbody>
    </table>
    <div class="affectationspagination">
    {{ knp_pagination_render(affectations) }}
    </div>
{% endblock %}

templates/affectations/new.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Create Affectation{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Create Affectation</h1>

    {{ include('affectations/_form.html.twig') }}

    <a href="{{ path('app_affectations_index') }}" class="editlink">Back</a>
{% endblock %}

templates/affectations/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Affectations{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Affectations</h1>

    <table class="table" border="5" style="background-color: rgb(29,118,157,0.6)">
        <tbody>
            <tr>
                <th>ID Terrain</th>
                <td>{{ affectation.id }}</td>
            </tr>
            <tr>
                <th>Nom Technicien</th>
                <td>{{ affectation.technicien }}</td>
            </tr>
            <tr>
                <th>Date Debut</th>
                <td>{{ affectation.dateDebut ? affectation.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date Fin</th>
                <td>{{ affectation.dateFin ? affectation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_affectations_index') }}"class="editlink">Back</a>

    <a href="{{ path('app_affectations_edit', {'id': affectation.id}) }}" class="editlink">Edit</a>

    {{ include('affectations/_delete_form.html.twig') }}
{% endblock %}

templates/affectations/stat.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Statistiques{% endblock %}


{% block body %}
<link rel="stylesheet" href="{{asset('back/css/styleTech.css')}}" type="text/css"> 
    <h1>Statistiques</h1>
    
    <a href="{{ path('app_affectations_index') }}" class="editlink">Back</a>

    <canvas id="categories" width="400" height="100"></canvas></div>
    

 {% block javascripts %}
<script>
    let categories = document.querySelector("#categories")
    let categGraph = new Chart(categories, {
        type: "doughnut",
        data: {
            labels: {{ technom|raw }},
            datasets: [{
                label: "Répartition des catégories",
                data: {{ nbr|raw }},
                
            backgroundColor: [
                '#FF6384',
                '#36A2EB',
                '#FFCE56',
                '#4BC0C0',
                '#E7E9ED',
                '#FF9F40',
                '#8E5EA2',
                '#3e95cd',
                '#8e5ea2',
                '#3cba9f',
                '#e8c3b9',
                '#c45850'
            ]
            }]   
        }
    })
</script>

{% endblock %}

{% endblock %}